### ISSUE TITLE
Error when installing Zimlet

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/zimbra-addon#8]
### Version information
N/A

### Steps to replicate

1. Client downloaded zimlet to a Mac
2. Unzipped the file, customized it as described in the KB
3. Added to a zip file and renamed
4. Uploaded the zimlet to one of the mailstore servers
5. Moved it to /opt/zimbra/zimlets/ and ran the deploy command

### Actual result
```
zimbra@mail05 ~]$ /opt/zimbra/bin/zmzimletctl deploy /opt/zimbra/zimlets/com_zimbra_spamexperts.zip

[] INFO: Deploying Zimlet com_zimbra_spamexperts in LDAP.

[] INFO: Installing Zimlet com_zimbra_spamexperts on this host.

[] INFO: Upgrading Zimlet com_zimbra_spamexperts to 1.2

[] INFO: Installing Zimlet config for com_zimbra_spamexperts

[] INFO: Adding Zimlet com_zimbra_spamexperts to COS default

[] INFO: Enabling Zimlet com_zimbra_spamexperts

[] INFO: Deploying on service node mail04.mxof.net

[] INFO: post to server mail04.mxof.net, data size 10718

[] INFO: deploy failed on service node mail04.mxof.net

com.zimbra.common.soap.SoapFaultException: system failure: error deploying Zimlet

ExceptionId:qtp1286783232-37177:1516669373836:ff7335bcdb78a077

Code:service.FAILURE

at com.zimbra.common.soap.Soap12Protocol.soapFault(Soap12Protocol.java:90)

at com.zimbra.common.soap.SoapTransport.extractBodyElement(SoapTransport.java:366)

at com.zimbra.common.soap.SoapTransport.parseSoapResponse(SoapTransport.java:339)

at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:267)

at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:173)

at com.zimbra.common.soap.SoapTransport.invoke(SoapTransport.java:419)

at com.zimbra.common.soap.SoapTransport.invoke(SoapTransport.java:382)

at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.soapDeployZimlet(ZimletUtil.java:1624)

at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletOnServiceNode(ZimletUtil.java:1561)

at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletRemotely(ZimletUtil.java:1498)

at com.zimbra.cs.zimlet.ZimletUtil.deployZimletRemotely(ZimletUtil.java:1253)

at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1911)

at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2007)

com.zimbra.common.soap.SoapFaultException: system failure: error deploying Zimlet

ExceptionId:qtp1286783232-37177:1516669373836:ff7335bcdb78a077

Code:service.FAILURE

at com.zimbra.common.soap.Soap12Protocol.soapFault(Soap12Protocol.java:90)

at com.zimbra.common.soap.SoapTransport.extractBodyElement(SoapTransport.java:366)

at com.zimbra.common.soap.SoapTransport.parseSoapResponse(SoapTransport.java:339)

at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:267)

at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:173)

at com.zimbra.common.soap.SoapTransport.invoke(SoapTransport.java:419)

at com.zimbra.common.soap.SoapTransport.invoke(SoapTransport.java:382)

at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.soapDeployZimlet(ZimletUtil.java:1624)

at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletOnServiceNode(ZimletUtil.java:1561)

at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletRemotely(ZimletUtil.java:1498)

at com.zimbra.cs.zimlet.ZimletUtil.deployZimletRemotely(ZimletUtil.java:1253)

at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1911)

at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2007)

[] ERROR: Error

com.zimbra.common.soap.SoapFaultException: system failure: error deploying Zimlet

ExceptionId:qtp1286783232-37177:1516669373836:ff7335bcdb78a077

Code:service.FAILURE

at com.zimbra.common.soap.Soap12Protocol.soapFault(Soap12Protocol.java:90)

at com.zimbra.common.soap.SoapTransport.extractBodyElement(SoapTransport.java:366)

at com.zimbra.common.soap.SoapTransport.parseSoapResponse(SoapTransport.java:339)

at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:267)

at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:173)

at com.zimbra.common.soap.SoapTransport.invoke(SoapTransport.java:419)

at com.zimbra.common.soap.SoapTransport.invoke(SoapTransport.java:382)

at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.soapDeployZimlet(ZimletUtil.java:1624)

at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletOnServiceNode(ZimletUtil.java:1561)

at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletRemotely(ZimletUtil.java:1498)

at com.zimbra.cs.zimlet.ZimletUtil.deployZimletRemotely(ZimletUtil.java:1253)

at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1911)

at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2007)

[zimbra@mail05 ~]$
```

### Expected result
The addon should be installed.

### Other notes
Whmcs ticket [690062](https://my.spamexperts.com/admin/supporttickets.php?action=view&id=193994)

**Comment by claudiapetre** [comment]
We noticed the addon can't be installed if, for Mac OS, the zip archive wasn't created from cmd. From the directory where you unzipped the addon, please execute the following

zip com_zimbra_spamexperts.zip *

This will create you the archive. Try to use it as usually and let us know if the issue was solved.

We test this addon by creating the zip file on others environments (Windows, Ubuntu) and there are no issues.

**Comment by SebaDA** [comment]
The zimlet cannot be removed: 

`com.zimbra.common.service.ServiceException: system failure: error occurred when deleting zimlet directory

Caused by: com.zimbra.cs.zimlet.ZimletException: Zimlet name may contain only letters, numbers and the following symbols: '.', '-' and '_' `

`/opt/zimbra/bin/zmzimletctl undeploy /opt/zimbra/zimlets/com_zimbra_spamexperts.zip

[] INFO: Uninstalling Zimlet /opt/zimbra/zimlets/com_zimbra_spamexperts.zip from LDAP.

[] INFO: undeploying zimlet /opt/zimbra/zimlets/com_zimbra_spamexperts.zip

com.zimbra.common.service.ServiceException: system failure: error occurred when deleting zimlet directory

ExceptionId:main:1517093083160:f64c9dd09a19b648

Code:service.FAILURE

at com.zimbra.common.service.ServiceException.FAILURE(ServiceException.java:286)

at com.zimbra.cs.zimlet.ZimletUtil.undeployZimletLocally(ZimletUtil.java:808)

at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1918)

at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2007)

Caused by: com.zimbra.cs.zimlet.ZimletException: Zimlet name may contain only letters, numbers and the following symbols: '.', '-' and '_'

at com.zimbra.cs.zimlet.ZimletException.INVALID_ZIMLET_NAME(ZimletException.java:48)

at com.zimbra.cs.zimlet.ZimletUtil.getZimletRootDir(ZimletUtil.java:524)

at com.zimbra.cs.zimlet.ZimletUtil.undeployZimletLocally(ZimletUtil.java:802)

... 2 more

[] ERROR: Error

com.zimbra.common.service.ServiceException: system failure: error occurred when deleting zimlet directory

ExceptionId:main:1517093083160:f64c9dd09a19b648

Code:service.FAILURE

at com.zimbra.common.service.ServiceException.FAILURE(ServiceException.java:286)

at com.zimbra.cs.zimlet.ZimletUtil.undeployZimletLocally(ZimletUtil.java:808)

at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1918)

at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2007)

Caused by: com.zimbra.cs.zimlet.ZimletException: Zimlet name may contain only letters, numbers and the following symbols: '.', '-' and '_'

at com.zimbra.cs.zimlet.ZimletException.INVALID_ZIMLET_NAME(ZimletException.java:48)

at com.zimbra.cs.zimlet.ZimletUtil.getZimletRootDir(ZimletUtil.java:524)

at com.zimbra.cs.zimlet.ZimletUtil.undeployZimletLocally(ZimletUtil.java:802) `

**Comment by claudiapetre** [comment]
We advised client how to pack his addon and how to clean his system of remaining files. His issue couldn't be replicated on our testing servers.
